name: Build NixOS Image for Wormdingler

on:
  push:
    branches:
      - development
  pull_request:

jobs:
  build-wormdingler:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu-user-static binfmt-support gcc-aarch64-linux-gnu
        sudo update-binfmts --enable qemu-aarch64

    - name: Install Nix package manager
      run: |
        curl -L https://nixos.org/nix/install | sh

    - name: Build NixOS Image for Wormdingler
      env:
        NIX_PATH: nixpkgs=channel:nixos-unstable
      run: |
        . /home/runner/.nix-profile/etc/profile.d/nix.sh
        nix-build examples/installer/ --argstr device lenovo-wormdingler -A outputs.default

    - name: Upload ARM Image
      uses: actions/upload-artifact@v4
      with:
        name: nixos-wormdingler-image
        path: ./result
