name: Build strongbad rootfs

on:
  push:
    branches:
      - development
jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up dependencies
        run: |
          sudo apt update
          sudo apt install -y qemu-user-static debootstrap mknod tar xz-utils

      - name: Run shimboot build
        run: |
          sudo chmod +x ./build_complete.sh
          sudo ./build_complete.sh strongbad unstable

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: strongbad-rootfs
          path: ./output/*  # Replace with the actual output path if different
